
package Ablak;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        //jButton1.setText("Klikk ide!");
        //this.setTitle("ablak neve");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") //layout dolgok felelősek a kinézetért
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        megjelenit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textNev = new javax.swing.JTextField();
        panelMegjelenit = new javax.swing.JPanel();
        labelMegjelenit = new javax.swing.JLabel();
        panelKor = new javax.swing.JPanel();
        olvas = new javax.swing.JRadioButton();
        nemOlvas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gui 1.0");

        megjelenit.setText("mutat");
        megjelenit.setToolTipText("");
        megjelenit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megjelenitActionPerformed(evt);
            }
        });

        jLabel1.setText("Név:");
        jLabel1.setToolTipText("");

        textNev.setToolTipText("");

        panelMegjelenit.setBorder(javax.swing.BorderFactory.createTitledBorder("Megjelenítés"));

        javax.swing.GroupLayout panelMegjelenitLayout = new javax.swing.GroupLayout(panelMegjelenit);
        panelMegjelenit.setLayout(panelMegjelenitLayout);
        panelMegjelenitLayout.setHorizontalGroup(
            panelMegjelenitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMegjelenitLayout.createSequentialGroup()
                .addComponent(labelMegjelenit, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMegjelenitLayout.setVerticalGroup(
            panelMegjelenitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMegjelenitLayout.createSequentialGroup()
                .addComponent(labelMegjelenit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelKor.setBorder(javax.swing.BorderFactory.createTitledBorder("Kor beállítása"));
        panelKor.setToolTipText("Kor beállítása");

        buttonGroup1.add(olvas);
        olvas.setText("már tudok olvasni");
        olvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olvasActionPerformed(evt);
            }
        });

        buttonGroup1.add(nemOlvas);
        nemOlvas.setText("6 év alatt, nem is tudok olvasni");
        nemOlvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemOlvasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKorLayout = new javax.swing.GroupLayout(panelKor);
        panelKor.setLayout(panelKorLayout);
        panelKorLayout.setHorizontalGroup(
            panelKorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nemOlvas)
                    .addComponent(olvas))
                .addContainerGap())
        );
        panelKorLayout.setVerticalGroup(
            panelKorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nemOlvas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(olvas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNev, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(megjelenit)
                            .addComponent(panelKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMegjelenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(megjelenit)
                .addGap(18, 18, 18)
                .addComponent(panelMegjelenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void megjelenitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megjelenitActionPerformed
        // TODO add your handling code here:
        /* Fent legenerálta az alábbi kódot, enélkül nem működik:
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });        */
        String nev = textNev.getText();
        //String uzenet = null;
        boolean checkBox1 = olvas.isSelected();
        boolean checkBox2 = nemOlvas.isSelected();
        if (nev.isEmpty() || (checkBox1 == false && checkBox2 == false)) {
            //feltételeket ő külön boolean returnös metódusokba írta
            JOptionPane.showMessageDialog(rootPane, "Nincs kitöltve egy kötelező mező!");
        } else {
            if (checkBox1 == true){
            //uzenet = "Szia %s".formatted(nev);
            labelMegjelenit.setIcon(null);
            String valasz = "<html>";
            valasz += "<h1>Kedves %s!</h1>".formatted(nev);
            valasz += "<p>A leírás itt olvasható...<br>";
            valasz += "<span style='color:red'>hamarosan!</span></p>";
            valasz += "</html>";
            labelMegjelenit.setText(valasz);
            } else {
                labelMegjelenit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ablak/kep1.jpg")));
            }
            
        }
        vezerlokAlapallba();
        
        //ha van szülő(rootPane), annak a közepén jelenik meg, ha null, akkor a képernyő közepén
        //megjelenit.setText("Klikk után");
    }//GEN-LAST:event_megjelenitActionPerformed

    private void nemOlvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemOlvasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nemOlvasActionPerformed

    private void olvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olvasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_olvasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { //névtelen függvény
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelMegjelenit;
    private javax.swing.JButton megjelenit;
    private javax.swing.JRadioButton nemOlvas;
    private javax.swing.JRadioButton olvas;
    private javax.swing.JPanel panelKor;
    private javax.swing.JPanel panelMegjelenit;
    private javax.swing.JTextField textNev;
    // End of variables declaration//GEN-END:variables

private void vezerlokAlapallba() {
    textNev.setText("");
    olvas.setSelected(false);
    nemOlvas.setSelected(false);
};

}


